---
- name: upd workers
  hosts: workers
  become: yes

  tasks:
  - name: Update all installed packages using APT module
    apt:
      name: '*'
      state: latest
      update_cache: yes
      only_upgrade: yes
    register: apt_update_status
  - debug:
      var: apt_update_status.changed
   
  - name: Remove packages not needed anymore
    apt:
      autoremove: yes
 
  - name: Reboot when packages were updated
    reboot:
      msg: "Reboot initiated by Ansible for kernel updates"
      post_reboot_delay: 180
      test_command: uptime
    when: apt_update_status.changed

- name: Upd masters
  hosts: masters
  become: yes

  tasks:
  - name: Update all installed packages using APT module
    apt:
      name: '*'
      state: latest
      update_cache: yes
      only_upgrade: yes
    register: apt_update_status
  - debug:
      var: apt_update_status.changed
   
  - name: Remove packages not needed anymore
    apt:
      autoremove: yes
