---
- hosts: all
  remote_user: admin-energo
  become: yes
  become_method: sudo
#  become_user: root
  gather_facts: yes
  connection: ssh
  
  tasks:
#====================================================== SWAP REMOVE =======
    - name: Make the Swap inactive
      command: swapoff -a

    - name: Remove Swap entry from /etc/fstab.
      lineinfile:
        dest: /etc/fstab
        regexp: swap
        state: absent
# ================================================= create File ==
    - name: Create containerd config file
      file:
        path: "/etc/modules-load.d/k8s.conf"
        state: "touch"
# ==== edit file ==
    - name: Add conf for containerd
      blockinfile:
        path: "/etc/modules-load.d/k8s.conf"
        block: |
          overlay
          br_netfilter

# ================================================= Run to Kernel ==
    - name: modprobe
      shell: |
        sudo modprobe overlay
        sudo modprobe br_netfilter

# ================================================= Write to Display ==
    - name: br_netfilter|overlay
      shell: lsmod | egrep "br_netfilter|overlay"
      register: varlsmod

    - debug:
        var: varlsmod.stdout_lines

# ================================================= Net  ==
    - name: Set system configurations for Kubernetes networking
      file:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        state: "touch"

    - name: Add conf for containerd
      blockinfile:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        block: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1

# ================================================= Run ==

    - name: Apply new settings
      command: sudo sysctl --system
...
